---
- name: Aktualizacja systemu
  hosts: serwery
  become: true
  become_user: root
  become_method: sudo

  tasks:
    - name: Kim jestem
      ansible.builtin.command: whoami
      register: who
      changed_when: false

    - name: Pokaż użytkownika
      ansible.builtin.debug:
        var: who.stdout

    - name: Aktualizacja listy pakietów
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
